build:
    dependencies:
        before:
            - sudo apt-get install -y poppler-utils
    environment:
        php:
            version: 7.4
            version: 8.0
    tests:
        override:
            - command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
              coverage:
                  file: 'clover.xml'
                  format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
